version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unparam
    - unused
  settings:
    dupl:
      threshold: 600
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        text: 'printf: non-constant format string in call to'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/shipengqi/jaguar
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
