package codegen

import (
	"github.com/shipengqi/action"

	"github.com/shipengqi/jaguar/internal/actions/codegen/options"
)

const (
	ActionName      = "codegen"
	ActionNameAlias = "cgen"
)

var errCodeDocTmpl = `# Error Codes

Error Codes Documentation generated by "{{.}}codegen -type=int -doc{{.}}", DO NOT EDIT.

## Features

如果返回结果中存在 {{.}}code{{.}} 字段，则表示调用 API 接口失败。例如：

{{.}}{{.}}{{.}}json
{
  "code": 100101,
  "message": "Database error"
}
{{.}}{{.}}{{.}}

上述返回中 {{.}}code{{.}} 表示错误码，{{.}}message{{.}} 表示该错误的具体信息。每个错误同时也对应一个 HTTP 状态码，比如上述错误码对应了 HTTP 状态码 500(Internal Server Error)。

## 错误码列表

IAM 系统支持的错误码列表如下：

| Identifier | Code | HTTP Code | Description |
| ---------- | ---- | --------- | ----------- |
`

var (
	errCodeTmpl = ``
)

func NewAction(opts *options.Options) *action.Action {
	act := &action.Action{
		Name: ActionName,
	}

	_ = act.AddAction()

	return act
}
