# apiserver configurations

# server configurations
server:
  mode: debug # server mode: release, debug, test，默认 release
  healthz: true # 是否开启健康检查，如果开启会安装 /healthz 路由，默认 true
  middlewares: recovery,requestid,logger,secure,nocache,cors # 加载的 gin 中间件列表，多个中间件，逗号(,)隔开
  max-ping-count: 3 # http 服务启动后，自检尝试次数，默认 3

# HTTP 配置
insecure:
  bind-address: 127.0.0.1 # 绑定的不安全 IP 地址，设置为 0.0.0.0 表示使用全部网络接口，默认为 127.0.0.1
  bind-port: 8080 # 提供非安全认证的监听端口，默认为 8080

# HTTPS 配置
#secure:
#  bind-address: 0.0.0.0 # HTTPS 安全模式的 IP 地址，默认为 0.0.0.0
#  bind-port: 0 # 使用 HTTPS 安全模式的端口号，设置为 0 表示不启用 HTTPS，默认为 8443
#  tls:
#    cert-file:  # 包含 x509 证书的文件路径，用 HTTPS 认证
#    private-key-file:  # TLS 私钥

# MySQL 数据库相关配置
mysql:
  host: 127.0.0.1:3306 # MySQL 机器 ip 和端口，默认 127.0.0.1:3306
  username: root # MySQL 用户名(建议授权最小权限集)
  password: 123456 # MySQL 用户密码
  database: demo # idm 系统所用的数据库名
  max-idle-connections: 100 # MySQL 最大空闲连接数，默认 100
  max-open-connections: 100 # MySQL 最大打开的连接数，默认 100
  max-connection-life-time: 10s # 空闲连接最大存活时间，默认 10s
  debug: true # GORM debug mode
  log-level: 4 # GORM log level, 1: silent, 2:error, 3:warn, 4:info

feature:
  enable-metrics: true # 开启 metrics, router: /debug/metrics
  profiling: true # 开启性能分析, router: /debug/pprof/ 查看程序栈、线程等系统信息，默认值为 true
