{
  "name": "{{.App.NormalizedName}}",
  "description": "{{.App.Name}} - Next.js SaaS Starter",
  "private": true,
  "scripts": {
    "dev": "next dev --turbopack",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "test": "echo \"no tests yet\" && exit 0",
    "db:setup": "npx tsx lib/db/setup.ts",
    "db:seed": "npx tsx lib/db/seed.ts",
    "db:generate": "drizzle-kit generate",
    "db:migrate": "drizzle-kit migrate",
    "db:studio": "drizzle-kit studio"
  },
  "dependencies": {
    "@tailwindcss/postcss": "4.1.7",
    "@types/node": "^22.15.18",
    "@types/react": "19.1.4",
    "@types/react-dom": "19.1.5",
    "autoprefixer": "^10.4.21",
    "bcryptjs": "^3.0.2",
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "dotenv": "^16.5.0",
    "drizzle-kit": "^0.31.1",
    "drizzle-orm": "^0.43.1",
    "jose": "^6.0.11",
    "lucide-react": "^0.511.0",
    "next": "15.6.0-canary.59",
    "postcss": "^8.5.3",
    "postgres": "^3.4.5",
    "radix-ui": "^1.4.2",
    "react": "19.1.0",
    "react-dom": "19.1.0",
    "server-only": "^0.0.1",
    "stripe": "^18.1.0",
    "swr": "^2.3.3",
    "tailwind-merge": "^3.3.0",
    "tailwindcss": "4.1.7",
    "tw-animate-css": "^1.3.0",
    "typescript": "^5.8.3",
    "zod": "^3.24.4"
  }
}
