name: "e2e test"
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
      - "README.md"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true

      - name: Build CLI
        run: make build

      - name: Upload jaguar binary
        uses: actions/upload-artifact@v4
        with:
          name: jaguar-bin
          path: _output/linux/amd64/bin/jaguar
          retention-days: 1

  run-e2e-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Download jaguar binary
        uses: actions/download-artifact@v4
        with:
          name: jaguar-bin
          path: _output/linux/amd64/bin

      - name: Make binary executable
        run: chmod +x _output/linux/amd64/bin/jaguar

      - name: Run E2E tests
        run: make e2e
