name: golangci-lint
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
permissions:
  contents: read

jobs:
  golangci:
    strategy:
      matrix:
        go: [ '1.25', '1.26', '1.27' ]
        os: [ ubuntu-latest, windows-latest ]
    permissions:
      contents: read
      pull-requests: read
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          args: --timeout=10m
          version: latest
